repos:
  - repo: local 
    hooks:
      - id: shfmt
        name: Sh (shell formatter)
        description: This hook checks shell files with shfmt.
        entry: bash -c 'for arg in "$@"; do nix shell nixpkgs#shfmt --command shfmt -w $arg; done;' --
        language: system
        types_or: [shell, executable]
      - id: gitleaks
        name: Gitleaks (secret scanner)
        description: This hook checks the existence of secrets.
        entry: bash -c 'nix shell nixpkgs#gitleaks --command gitleaks git --pre-commit --staged --redact --no-banner --verbose 2> /dev/null; nix shell nixpkgs#gitleaks --command gitleaks git --redact --no-banner --verbose 2> /dev/null'
        language: system
        pass_filenames: false
